name: build-deploy-azure-razor-movie
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore Nuget packages
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build
      - name: Publish
        run: dotnet publish RazorPagesMovie/RazorPagesMovie.csproj -c Release -o website
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: razor-movie
          path: website/**
          if-no-files-found: error